### ISSUE TITLE
Mesh shortcut key 'w' from Segmentor works in ninjato

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/ninjato#118]
When trying to determine which features might have shortcuts, I noticed that 'w' switches the 3D view to a mesh mode. I was not able to get out of this mode unless I refreshed the assignment page.

![Issue- Mesh shortcut key works](https://user-images.githubusercontent.com/3201990/186702319-663b4476-f82d-4999-9a41-8850086c3135.png)

**Comment by davidborland** [comment]
Fixed
