### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by davidborland** [RENCI/ninjato#152]
Add training modules:
- Multiple "levels" of curated assignments
- Include standard editing, splitting merging, claiming, etc.
- Need gold standard masks, can compute dice score. Don't advance until meet dice score threshold
- Earn badges for each level
- When finished, eligible to do "real" work.

**Comment by JustKeepClimbing** [comment]
@davidborland want to discuss this one at our next cloud dev meeting (Nov. 2nd)?

**Comment by davidborland** [comment]
Sounds good

**Comment by davidborland** [comment]
Dice score:
* Add gold standard mask to girder
* Compute dice score in client - show progress visualization, enable to update with button click
* Overall dice score for full training volume vs. relative dice score for current assignment?

**Comment by davidborland** [comment]
Implemented. Will create new issue for Training Modules.
