### ISSUE TITLE
Exploring to automatically unassign any assignment/reviews for a user when the user is removed from the system

### ISSUE THREAD

**Issue by hyi** [RENCI/ninjato#182]
Exploring to see whether a girder plugin can be written to customize what happens when a user is removed from the system first. If that is too difficult, a script can be written outside girder using girder client to achieve this.

**Comment by hyi** [comment]
Addressing this issue can address the specific issue #180: Move updated user annotation assignment mask to the general open for review queue rather than to the reviewer who reviewed the assignment mask initially. Merging them into this single more general issue and close the other issue #180.

**Comment by davidborland** [comment]
Addressed #180 instead, so this can be closed.
