### ISSUE TITLE
Submitted assignments still showing active

### ISSUE THREAD

**Issue by JustKeepClimbing** [RENCI/ninjato#227]
Several ninjas (refining tab only), have reported that after submitting an assignment, they still see the assignments as 'active' in the queue. Attached is one example (IDs 917 and 1409). Assignments cannot get pushed to the review stage as a result.

![IDs917and1409](https://user-images.githubusercontent.com/3201990/211875070-49e7b1b7-ce52-44e7-ac4e-0ab7f387bf39.png)

**Comment by JustKeepClimbing** [comment]
Adding more examples here:
<img width="659" alt="image (3)" src="https://user-images.githubusercontent.com/3201990/211895360-e6c3701e-e431-490f-a402-22cd328380f2.png">

**Comment by hyi** [comment]
Fixed by fixing timestamp comparisons. Closing.
