### ISSUE TITLE
Updating subvolume and assignments

### ISSUE THREAD

**Issue by davidborland** [RENCI/ninjato#274]
1. When merging with subvolume after submit or verify, only update labels that belong to the assignment. Note that this means clearing any labeled voxels in the subvolume that are not labeled in the assignment, as well as setting labels that are in the assignment.
2. Update current assignments after merging with subvolume, overwriting with changes, but keeping user edits.
3. Also do this for assignment that have been submitted, but not yet verified.

**Comment by davidborland** [comment]
@hyi This was implemented and can be closed, correct?

**Comment by hyi** [comment]
@davidborland Yes. Closing.
